### ISSUE TITLE
"Image could not be loaded" - Old 3DS error

### ISSUE THREAD

**Issue by wuniversales** [rverseTeam/rverse2#17]
No image loading...
![image](https://user-images.githubusercontent.com/48658161/100676130-8b342d80-3368-11eb-954e-4e4928ba645a.png)
![image](https://user-images.githubusercontent.com/48658161/100676064-6dff5f00-3368-11eb-929e-086776b02c65.png)

**Comment by Repflez** [comment]
This is a known bug, but unfortunately, I lack of a console to be able to properly debug this issue

**Comment by TermOfficial** [comment]
Would you like me to use my console to help debug it?

**Comment by TermOfficial** [comment]
Yes, I know this issue is old, it's just been here for awhile though,

**Comment by wuniversales** [comment]
> ¿Le gustaría que use mi consola para ayudar a depurarlo?



> Would you like me to use my console to help debug it?

It would be good if you contributed it, to be able to fix it. 
I tried, but I don't know in the end what happened, that I couldn't debug it. :(

**Comment by Repflez** [comment]
At this point of time, this has been fixed now
