### ISSUE TITLE
[BUG] Change UI Languaje to Spanish breaks rverse options

### ISSUE THREAD

**Issue by gomgo-github** [rverseTeam/rverse2#49]
Hi! Before writing anything, i'm using a N3DSXL with Luma v12.0.1-3gxldr, with 11.16.0-49E Firmware and Rverse v4.0.0 (Latest version from Universal Updater as 23/04/2023), i got this error with 2 different consoles with the same specs (N3DSXL, Luma v12.0-3gxldr, etc)

I found that when someone changes it's UI Languaje to Spanish (from User(Mii Icon)>Settings>rverse Settings>UI Languaje) you can't go to the User option or any option under User(Mii Icon)> because it won't load, and after waiting, every button will be completely useless (if you click on the feed button, nothing happens, if you click on the communities), you need to press Home button and restart rverse to get it working again.

I hope you guys can fix this error and good luck, except this little bug everything works fine, if you need any other information about this bug to fix it (logs or whatever) i would send them. 

Thanks

**Comment by Repflez** [comment]
Fixed now in 770eb4f99c302b5ce7cf69bc2aadff29da331ebf
