### ISSUE TITLE
Error code: 015-5016

### ISSUE THREAD

**Issue by Minecraftplayer20** [rverseTeam/rverse2#66]
I keep getting an error that says 015-5016 and I googled it I can't find anything talking about it. Rverse worked perfectly fine before.  I do have game patching enabled and rverse installed.

**Comment by lisbonjoker** [comment]
Servers are seemingly down, @Repflez seems to be busy, so the best option is to wait until they can work on it.

**Comment by Minecraftplayer20** [comment]
I fixed it

**Comment by 18209550** [comment]
this happens again at 3/29/24 9:57 PM EDT (us)
