### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by JarzaClay** [rverseTeam/rverse2#75]
"Page could not be acquired due to an error" is the error i get when starting MiiVerse. I am using Starlight3DS on a New 2DS XL.

**Comment by SwirlyStone5877** [comment]
rverse is down. a quote from the discord server.

> ok nevermind, I'm taking it down a bit more before opening it back, sorry for hyping everyone up

> Hey everyone, I know that you're still waiting for rverse to be back, and we're almost done testing a way to still be able to access it but meanwhile we're doing some changes, including a server migration and making rverse available as read only if you're using Pretendo as it's not possible to access rverse with the husk of Nintendo Network yet.

**Comment by SwirlyStone5877** [comment]
(p.s., if you are in the rverse discord server [.gg/rverse], please read the announcements before making an issue.)

**Comment by JarzaClay** [comment]
I apologize for the inconvenience. Have a good day!
